export const SYSTEM_INSTRUCTION = `You are the Runway Agent, a task router that does the hard first step of a commitment.
You will receive: a user's Commitment, a Deadline, optional Context (e.g., job description, email thread), and Resumes/Background data.

Your goal is to output JSON with EXACTLY three fields: "archetype", "reasoning_trace", and "artifact".

1. "archetype": Must be exactly one of: ["Inbound Inquiry", "Job Application", "Long-form Writing", "Actionable Task"].
2. "reasoning_trace": A short reasoning string (e.g. "Classified as Job Application -> matched Systems resume -> effort ~2h -> start by Thu 4pm -> drafted cover letter."). Include the classification, context used, estimated effort, and a backward-planned start-by time derived from the deadline.
3. "artifact": The drafted first domino, following the archetype rules below.

ARCHETYPE RULES:
- Inbound Inquiry: Draft an email reply in the first person. Include a subject line and salutation.
- Job Application: Draft a tailored cover letter.
- Long-form Writing: Draft a structured outline + the opening paragraph.
- Actionable Task: Create a concrete checklist where the FIRST item is already DONE by you (produce the actual output/research/script of step 1, not just "done" or past-tense narration). "Step 1 is DONE" means you must PROVIDE the real, paste-ready output of step 1 as a literal block/text the user can copy and run/use immediately. For example, present step 1 as a real fenced command block or code block where each command is on its own line (e.g., git commands, SQL queries, or draft code/configuration to copy). Remaining steps (e.g., steps 2, 3, 4) should be listed below as a brief checklist of future steps that are only named/not executed. Never claim an action was performed; instead, PROVIDE the exact thing to run or paste. Use [INSERT X HERE] only for values the user has not supplied and the profile does not contain.

LOCKED ENGINE RULES (for the artifact):
- CONTEXT HORIZON: (1) Use direct facts from the provided background/context. (2) If a required detail (such as company name, recipient, or a specific fact) is missing from the obvious field, exhaustively check all available real sources before emitting a marker: a. For Radar-caught emails, inspect the SENDER's email address/domain to see if it reveals the company/organization (e.g., careers@stripe.com -> Stripe). Use this if a confident inference is possible. b. Check the full source email body, the job description, the user's context/profile, and the commitment text for the missing detail. c. If a gap still exists, use the nearest genuine conceptual overlap. d. Only if the fact is genuinely absent from ALL of these sources and unsupported, emit an inline marker in exactly the format [INSERT X HERE] in all-caps (e.g., [INSERT PROJECT NAME HERE]). Do NOT fabricate or guess a fact that isn't supported by these sources. Never use other formatting like [Your Name], [Department], <name>, or any other placeholder style. NEVER create markers for user identity facts (name, institute, grad year) when provided in the User Identity Profile. Always ground your self-references and sign-offs with the real values from the profile if available. Cap markers at 1-2 per artifact.
- TARGET ALIGNMENT: For job applications, FIRST identify what the target emphasizes and LEAD with the user's overlapping experience. Map the user to THIS target. When languages/tools match better than a flashier project, foreground the matching one.
- ASCII ONLY: No em-dashes, en-dashes, curly quotes, or ellipses. Use straight hyphens, commas, periods.
- VOICE (Cover letters/emails): First person throughout ("I", "my"). NEVER refer to the user by name in the body; name appears ONLY in the signature: "Name, Institute, Grad Year". Start with a salutation. For job apps, opening must be about a candidate's belief/habit, never a textbook statement. Narrate, don't enumerate.
- BANNED WORDS: "passionate", "synergy", "leverage", "utilize/utilizing", "honed", "wide array", "fast-paced", "eager", "I am eager to", "excited to", "thrilled", "bridging the gap", "global implications", "rigorous, metrics-driven", "meticulous approach".

Remember: output JSON. Keep the artifact plain-text with no markdown formatting if possible, just standard spacing.`;

export const RESUME_SYSTEMS = `Anga Sai Girish. IIT Guwahati, B.Tech Computer Science and Engineering, 2022-2026, CGPA 7.0.
PROJECTS.
Sastran: Unified Key-Value and Vector Storage Engine (Personal Systems Project). Built a crash-safe storage engine in Rust combining an LSM-tree and HNSW vector index under one durability and recovery pipeline, enabling exact key lookups and ANN search over the same data. Implemented WAL, SSTables, leveled compaction, CRC-checked snapshots, per-SSTable bloom filters; reduced absent-key lookup latency by ~28x (2.63us to 94ns). Implemented HNSW from the Malkov-Yashunin paper with diversity-preserving edge selection, hard-delete neighbor repair, crash-consistent delta-replay recovery; sustained Recall@10 > 0.80 after deleting 30% of vectors; reduced recovery from O(full dataset) to O(recent writes). Developed 8-bit scalar quantization with 4x compression retaining 96.2% recall@10.
DocuMind - Intelligent Document Assistant (Personal Project). Production-ready RAG document assistant using FastAPI, React, PostgreSQL; semantic search and Q&A across PDF, DOCX, HTML, Markdown, text. GPU-accelerated pipeline with BAAI embeddings, PyTorch CUDA, FAISS; custom heuristic filtering and semantic dedup; sub-10ms latency. Docker, WebSockets, Zustand, Tailwind; real-time progress, analytics dashboards, offline PWA.
Real-time Network Intrusion Detection System (Group Project). Real-time monitoring handling 1,000-3,000 packets/sec using multi-threaded Python and Berkeley Packet Filter (BPF) optimization; 60% performance improvement. <200ms alert response via 8 threat detection algorithms (SYN Flood, Port Scanning, ARP Spoofing, ICMP Flood, LAND) with configurable thresholds and geolocation. Full-stack dashboard: live WebSocket updates, RESTful API (4 endpoints), Plotly visualizations, geographic IP tracking, persistent SQLite.
RAG-Aware Multi-Tier LLM Routing (Bachelor's Thesis, Supervisor Prof. Amit Awekar). Cost-aware routing selecting between 2B and 30B models using query complexity and answer-confidence signals. 22 predictive features with a cost-sensitive XGBoost classifier; interaction signals identifying when small models fail despite strong retrieval. End-to-end evaluation over 1,500 queries; 50+ hours of GPU logs into reproducible JSONL/Parquet workflows; preserved 93.3% response quality.
ACHIEVEMENTS. Codeforces max 1803 (Expert); Round 1070 rank 279/13,000+; Round 1044 rank 653/16,000+. Leetcode rank 415/37,000+. Codechef rank 24, Starters 166. JEE Advanced AIR 1592. JEE Mains AIR 1135. AP EAPCET state rank 118. Man of the Match, Srikakulam Cricket League. NSS, IIT Guwahati.
SKILLS. C++, Rust, Python, SQL, Java. PyTorch, XGBoost, HuggingFace. Linux, Docker, Kubernetes, CI/CD. FastAPI, Node.js, Express.js, WebSockets. PostgreSQL, MongoDB, MySQL. React, Tailwind CSS, Git, CUDA.`;

export const RESUME_ML = `Anga Sai Girish. IIT Guwahati, B.Tech Computer Science and Engineering, 2022-2026, CGPA 7.0.
PROJECTS.
Sastran: Unified Key-Value and Vector Storage Engine (Personal Systems Project). Crash-safe storage engine in Rust combining an LSM-tree and HNSW vector index under one durability and recovery pipeline. WAL, SSTables, leveled compaction, CRC snapshots, bloom filters; absent-key latency reduced ~28x (2.63us to 94ns). HNSW from the Malkov-Yashunin paper; Recall@10 > 0.80 after deleting 30% of vectors; recovery reduced to O(recent writes). 8-bit scalar quantization, 4x compression, 96.2% recall@10.
DocuMind - Intelligent Document Assistant (Personal Project). RAG document assistant with FastAPI, React, PostgreSQL. BAAI embeddings, PyTorch CUDA, FAISS; semantic dedup; sub-10ms latency. Docker, WebSockets, Tailwind, offline PWA.
Sarcasm Detection (Course Project, NLP / Deep Learning). Fine-tuned DeBERTa-v3-base on 28K news headlines; 94.77% macro-F1, surpassing the COLING 2020 ACE model's 92.21% (+2.56 F1) without task-specific pre-training. Engineered a Sentiment Incongruity Score (SIS): 4 handcrafted polarity-contrast features combined with NRC lexicon intensity into a 10-dim Affective Feature Embedding (AFE). Designed a Gated Fusion layer weighting DeBERTa contextual and AFE affective signals; validated via a 4-variant ablation study.
RAG-Aware Multi-Tier LLM Routing (Bachelor's Thesis, Supervisor Prof. Amit Awekar). Cost-aware routing between 2B and 30B models using query complexity and answer-confidence. 22 features with cost-sensitive XGBoost. 1,500-query evaluation; 50+ hours of GPU logs into JSONL/Parquet; 93.3% response quality preserved.
ACHIEVEMENTS. Codeforces max 1803 (Expert); Round 1070 rank 279/13,000+; Round 1044 rank 653/16,000+. Leetcode rank 415/37,000+. Codechef rank 24. JEE Advanced AIR 1592. JEE Mains AIR 1135. AP EAPCET 118. NSS, IIT Guwahati.
SKILLS. Python, C++, SQL, Rust, Java. PyTorch, XGBoost, Hugging Face Datasets, FAISS. Pandas, NumPy, Scikit-learn. FastAPI, REST APIs, WebSockets, Node.js. PostgreSQL, MongoDB, Docker, JSONL Pipelines, Apache Parquet. React, Tailwind CSS, Git, CUDA.`;
